INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'A', '', False, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'B', 'À', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'C', 'À L''', False, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'D', 'À LA', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'E', 'AU', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'F', 'AUX', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'G', 'CHEZ', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'H', 'D''', False, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'I', 'DE', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'J', 'DE L''', False, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'K', 'DE LA', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'L', 'DES', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'M', 'DU', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'N', 'L''', False, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'O', 'LA', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'P', 'LE', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'Q', 'LES', True, True);
INSERT INTO lane_generic_code (id, code, description, add_white_space_after, is_active) VALUES (uuid_generate_v4(), 'R', 'THE', True, True);