//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survi.Prevention.ServiceLayer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Survi.Prevention.ServiceLayer.Localization.EnumResource", typeof(EnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauche.
        /// </summary>
        internal static string CourseLaneDirection_Left {
            get {
                return ResourceManager.GetString("CourseLaneDirection_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droite.
        /// </summary>
        internal static string CourseLaneDirection_Right {
            get {
                return ResourceManager.GetString("CourseLaneDirection_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout droit.
        /// </summary>
        internal static string CourseLaneDirection_StraightAhead {
            get {
                return ResourceManager.GetString("CourseLaneDirection_StraightAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au dessus du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_Above {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au coin du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_AtCorner {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_AtCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au bout du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_AtEnd {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_AtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À l&apos;adresse.
        /// </summary>
        internal static string FireHydrantAddressLocationType_AtTheAddress {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_AtTheAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À l&apos;arrière du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_BackWard {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_BackWard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En face du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_InFront {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_InFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Près du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_Near {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_Near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À Côté du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_NextTo {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_NextTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En dessous du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_Under {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible du.
        /// </summary>
        internal static string FireHydrantAddressLocationType_VisibleFrom {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType_VisibleFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étage.
        /// </summary>
        internal static string floor {
            get {
                return ResourceManager.GetString("floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détaché.
        /// </summary>
        internal static string GarageType_Detached {
            get {
                return ResourceManager.GetString("GarageType_Detached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string GarageType_No {
            get {
                return ResourceManager.GetString("GarageType_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string GarageType_Yes {
            get {
                return ResourceManager.GetString("GarageType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plancher.
        /// </summary>
        internal static string ParticularRiskType_Floor {
            get {
                return ResourceManager.GetString("ParticularRiskType_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondation.
        /// </summary>
        internal static string ParticularRiskType_Foundation {
            get {
                return ResourceManager.GetString("ParticularRiskType_Foundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toit.
        /// </summary>
        internal static string ParticularRiskType_Roof {
            get {
                return ResourceManager.GetString("ParticularRiskType_Roof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mur.
        /// </summary>
        internal static string ParticularRiskType_Wall {
            get {
                return ResourceManager.GetString("ParticularRiskType_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secteur.
        /// </summary>
        internal static string sector {
            get {
                return ResourceManager.GetString("sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mur.
        /// </summary>
        internal static string wall {
            get {
                return ResourceManager.GetString("wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
