//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survi.Prevention.ApiClient.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Survi.Prevention.ApiClient.Localization.EntityLocalization", typeof(EntityLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de panneau d&apos;alarme.
        /// </summary>
        public static string AlarmPanelType {
            get {
                return ResourceManager.GetString("AlarmPanelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bâtiment.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panneau d&apos;alarme de bâtiment.
        /// </summary>
        public static string BuildingAlarmPanel {
            get {
                return ResourceManager.GetString("BuildingAlarmPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomalie de bâtiment.
        /// </summary>
        public static string BuildingAnomaly {
            get {
                return ResourceManager.GetString("BuildingAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images d&apos;anomalie de bâtiment.
        /// </summary>
        public static string BuildingAnomalyPicture {
            get {
                return ResourceManager.GetString("BuildingAnomalyPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de bâtiment enfant.
        /// </summary>
        public static string BuildingChildType {
            get {
                return ResourceManager.GetString("BuildingChildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact de bâtiment.
        /// </summary>
        public static string BuildingContact {
            get {
                return ResourceManager.GetString("BuildingContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcours.
        /// </summary>
        public static string BuildingCourse {
            get {
                return ResourceManager.GetString("BuildingCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue du parcours.
        /// </summary>
        public static string BuildingCourseLane {
            get {
                return ResourceManager.GetString("BuildingCourseLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail de bâtiment.
        /// </summary>
        public static string BuildingDetail {
            get {
                return ResourceManager.GetString("BuildingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borne de bâtiment.
        /// </summary>
        public static string BuildingFireHydrant {
            get {
                return ResourceManager.GetString("BuildingFireHydrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matière dangeureuse de bâtiment.
        /// </summary>
        public static string BuildingHazardousMaterial {
            get {
                return ResourceManager.GetString("BuildingHazardousMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risque particulier de bâtiment.
        /// </summary>
        public static string BuildingParticularRisk {
            get {
                return ResourceManager.GetString("BuildingParticularRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image de risque particulier de bâtiment.
        /// </summary>
        public static string BuildingParticularRiskPicture {
            get {
                return ResourceManager.GetString("BuildingParticularRiskPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNAP de bâtiment.
        /// </summary>
        public static string BuildingPersonRequiringAssistance {
            get {
                return ResourceManager.GetString("BuildingPersonRequiringAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gicleur de bâtiment.
        /// </summary>
        public static string BuildingSprinkler {
            get {
                return ResourceManager.GetString("BuildingSprinkler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de bâtiment.
        /// </summary>
        public static string BuildingType {
            get {
                return ResourceManager.GetString("BuildingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipalité.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de municipalité.
        /// </summary>
        public static string CityType {
            get {
                return ResourceManager.GetString("CityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de résistance au feu (construction).
        /// </summary>
        public static string ConstructionFireResistanceType {
            get {
                return ResourceManager.GetString("ConstructionFireResistanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de construction.
        /// </summary>
        public static string ConstructionType {
            get {
                return ResourceManager.GetString("ConstructionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRC.
        /// </summary>
        public static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction de rue.
        /// </summary>
        public static string CourseLaneDirection {
            get {
                return ResourceManager.GetString("CourseLaneDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borne incendie.
        /// </summary>
        public static string FireHydrant {
            get {
                return ResourceManager.GetString("FireHydrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;adresse de borne incendie.
        /// </summary>
        public static string FireHydrantAddressLocationType {
            get {
                return ResourceManager.GetString("FireHydrantAddressLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raccord de borne incendie.
        /// </summary>
        public static string FireHydrantConnection {
            get {
                return ResourceManager.GetString("FireHydrantConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de raccord de borne incendie.
        /// </summary>
        public static string FireHydrantConnectionType {
            get {
                return ResourceManager.GetString("FireHydrantConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;emplacement de borne incendie.
        /// </summary>
        public static string FireHydrantLocationType {
            get {
                return ResourceManager.GetString("FireHydrantLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de borne d&apos;incendie.
        /// </summary>
        public static string FireHydrantType {
            get {
                return ResourceManager.GetString("FireHydrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service incendie.
        /// </summary>
        public static string FireSafetyDepartment {
            get {
                return ResourceManager.GetString("FireSafetyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserte de service incendie.
        /// </summary>
        public static string FireSafetyDepartmentCity {
            get {
                return ResourceManager.GetString("FireSafetyDepartmentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserte de service incendie.
        /// </summary>
        public static string FireSafetyDepartmentCityServing {
            get {
                return ResourceManager.GetString("FireSafetyDepartmentCityServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caserne .
        /// </summary>
        public static string Firestation {
            get {
                return ResourceManager.GetString("Firestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de garage.
        /// </summary>
        public static string GarageType {
            get {
                return ResourceManager.GetString("GarageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matière dangereuse.
        /// </summary>
        public static string HazardousMaterial {
            get {
                return ResourceManager.GetString("HazardousMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue.
        /// </summary>
        public static string Lane {
            get {
                return ResourceManager.GetString("Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code générique d&apos;une rue.
        /// </summary>
        public static string LaneGenericCode {
            get {
                return ResourceManager.GetString("LaneGenericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code public d&apos;une rue.
        /// </summary>
        public static string LanePublicCode {
            get {
                return ResourceManager.GetString("LanePublicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de mesure.
        /// </summary>
        public static string MeasureType {
            get {
                return ResourceManager.GetString("MeasureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;opérateur.
        /// </summary>
        public static string OperatorType {
            get {
                return ResourceManager.GetString("OperatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de risque particulier.
        /// </summary>
        public static string ParticularRiskType {
            get {
                return ResourceManager.GetString("ParticularRiskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de PNAP.
        /// </summary>
        public static string PersonRequiringAssistanceType {
            get {
                return ResourceManager.GetString("PersonRequiringAssistanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Région administrative.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau de risque.
        /// </summary>
        public static string RiskLevel {
            get {
                return ResourceManager.GetString("RiskLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de matériel de toiture.
        /// </summary>
        public static string RoofMaterialType {
            get {
                return ResourceManager.GetString("RoofMaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de toiture.
        /// </summary>
        public static string RoofType {
            get {
                return ResourceManager.GetString("RoofType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de revêtement.
        /// </summary>
        public static string Sidingtype {
            get {
                return ResourceManager.GetString("Sidingtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de gicleur.
        /// </summary>
        public static string SprinklerType {
            get {
                return ResourceManager.GetString("SprinklerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de réservoir de stockage.
        /// </summary>
        public static string StorageTankType {
            get {
                return ResourceManager.GetString("StorageTankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure.
        /// </summary>
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code d&apos;utilisation.
        /// </summary>
        public static string UtilisationCode {
            get {
                return ResourceManager.GetString("UtilisationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année du code d&apos;utilisation.
        /// </summary>
        public static string UtilizationCodeYear {
            get {
                return ResourceManager.GetString("UtilizationCodeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année .
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
