//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survi.Prevention.ApiClient.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Survi.Prevention.ApiClient.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansi code.
        /// </summary>
        internal static string AnsiCode {
            get {
                return ResourceManager.GetString("AnsiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call priority.
        /// </summary>
        internal static string CallPriority {
            get {
                return ResourceManager.GetString("CallPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity container.
        /// </summary>
        internal static string CapacityContainer {
            get {
                return ResourceManager.GetString("CapacityContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone number.
        /// </summary>
        internal static string CellphoneNumber {
            get {
                return ResourceManager.GetString("CellphoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code with 3 letters.
        /// </summary>
        internal static string Code3Letters {
            get {
                return ResourceManager.GetString("Code3Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeAlpha2 {
            get {
                return ResourceManager.GetString("CodeAlpha2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeAlpha3 {
            get {
                return ResourceManager.GetString("CodeAlpha3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cubf {
            get {
                return ResourceManager.GetString("Cubf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        internal static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is empty..
        /// </summary>
        internal static string EmptyValue {
            get {
                return ResourceManager.GetString("EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas inlet.
        /// </summary>
        internal static string GasInlet {
            get {
                return ResourceManager.GetString("GasInlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide number.
        /// </summary>
        internal static string GuideNumber {
            get {
                return ResourceManager.GetString("GuideNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Identifier.
        /// </summary>
        internal static string IdBuilding {
            get {
                return ResourceManager.GetString("IdBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City identifier.
        /// </summary>
        internal static string IdCity {
            get {
                return ResourceManager.GetString("IdCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City type identifier.
        /// </summary>
        internal static string IdCityType {
            get {
                return ResourceManager.GetString("IdCityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country identifier.
        /// </summary>
        internal static string IdCountry {
            get {
                return ResourceManager.GetString("IdCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County identifier.
        /// </summary>
        internal static string IdCounty {
            get {
                return ResourceManager.GetString("IdCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire hydrant identifier.
        /// </summary>
        internal static string IdFireHydrant {
            get {
                return ResourceManager.GetString("IdFireHydrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire hydrant connection type identifier.
        /// </summary>
        internal static string IdFireHydrantConnectionType {
            get {
                return ResourceManager.GetString("IdFireHydrantConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire safety department identifier.
        /// </summary>
        internal static string IdFireSafetyDepartment {
            get {
                return ResourceManager.GetString("IdFireSafetyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous material identifier.
        /// </summary>
        internal static string IdHazardousMaterial {
            get {
                return ResourceManager.GetString("IdHazardousMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane generic code identifier.
        /// </summary>
        internal static string IdLaneGenericCode {
            get {
                return ResourceManager.GetString("IdLaneGenericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public code identifier.
        /// </summary>
        internal static string IdPublicCode {
            get {
                return ResourceManager.GetString("IdPublicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure identifier.
        /// </summary>
        internal static string IdUnitOfMeasure {
            get {
                return ResourceManager.GetString("IdUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure diameter identifier.
        /// </summary>
        internal static string IdUnitOfMeasureDiameter {
            get {
                return ResourceManager.GetString("IdUnitOfMeasureDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is less than 0..
        /// </summary>
        internal static string InferiorToZeroValue {
            get {
                return ResourceManager.GetString("InferiorToZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the count must be greater than 1..
        /// </summary>
        internal static string InvalidCount {
            get {
                return ResourceManager.GetString("InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is invalid..
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizations.
        /// </summary>
        internal static string Localizations {
            get {
                return ResourceManager.GetString("Localizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure type.
        /// </summary>
        internal static string MeasureType {
            get {
                return ResourceManager.GetString("MeasureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is missing..
        /// </summary>
        internal static string MissingValue {
            get {
                return ResourceManager.GetString("MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value does not exist..
        /// </summary>
        internal static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other information.
        /// </summary>
        internal static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other number.
        /// </summary>
        internal static string OtherNumber {
            get {
                return ResourceManager.GetString("OtherNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other number extension.
        /// </summary>
        internal static string OtherNumberExtension {
            get {
                return ResourceManager.GetString("OtherNumberExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager code.
        /// </summary>
        internal static string PagerCode {
            get {
                return ResourceManager.GetString("PagerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager number.
        /// </summary>
        internal static string PagerNumber {
            get {
                return ResourceManager.GetString("PagerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number extension.
        /// </summary>
        internal static string PhoneNumberExtension {
            get {
                return ResourceManager.GetString("PhoneNumberExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Scian {
            get {
                return ResourceManager.GetString("Scian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security perimeter.
        /// </summary>
        internal static string SecurityPerimeter {
            get {
                return ResourceManager.GetString("SecurityPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply line.
        /// </summary>
        internal static string SupplyLine {
            get {
                return ResourceManager.GetString("SupplyLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank type.
        /// </summary>
        internal static string TankType {
            get {
                return ResourceManager.GetString("TankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of characters is.
        /// </summary>
        internal static string TooLong {
            get {
                return ResourceManager.GetString("TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        internal static string Wall {
            get {
                return ResourceManager.GetString("Wall", resourceCulture);
            }
        }
    }
}
