//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survi.Prevention.ApiClient.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Survi.Prevention.ApiClient.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abréviation.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations supplémentaires.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation.
        /// </summary>
        public static string AdressLocationType {
            get {
                return ResourceManager.GetString("AdressLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Ansi.
        /// </summary>
        public static string AnsiCode {
            get {
                return ResourceManager.GetString("AnsiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro d&apos;appartement.
        /// </summary>
        public static string AppartmentNumber {
            get {
                return ResourceManager.GetString("AppartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur du bâtiment.
        /// </summary>
        public static string BuildingValue {
            get {
                return ResourceManager.GetString("BuildingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorité d&apos;appel.
        /// </summary>
        public static string CallPriority {
            get {
                return ResourceManager.GetString("CallPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacité du réservoir.
        /// </summary>
        public static string CapacityContainer {
            get {
                return ResourceManager.GetString("CapacityContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone cellulaire.
        /// </summary>
        public static string CellphoneNumber {
            get {
                return ResourceManager.GetString("CellphoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string ChildType {
            get {
                return ResourceManager.GetString("ChildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lettre civique supérieure.
        /// </summary>
        public static string CivicLetterSupp {
            get {
                return ResourceManager.GetString("CivicLetterSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro civique.
        /// </summary>
        public static string CivicNumber {
            get {
                return ResourceManager.GetString("CivicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro civique supérieur.
        /// </summary>
        public static string CivicSupp {
            get {
                return ResourceManager.GetString("CivicSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code à trois chiffres.
        /// </summary>
        public static string Code3Letters {
            get {
                return ResourceManager.GetString("Code3Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code alpha 2.
        /// </summary>
        public static string CodeAlpha2 {
            get {
                return ResourceManager.GetString("CodeAlpha2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code alpha 3.
        /// </summary>
        public static string CodeAlpha3 {
            get {
                return ResourceManager.GetString("CodeAlpha3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenant.
        /// </summary>
        public static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source coordonnées.
        /// </summary>
        public static string CoordinatesSource {
            get {
                return ResourceManager.GetString("CoordinatesSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code d&apos;utilisation des biens-fonds.
        /// </summary>
        public static string Cubf {
            get {
                return ResourceManager.GetString("Cubf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamètre.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        public static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur vide..
        /// </summary>
        public static string EmptyValue {
            get {
                return ResourceManager.GetString("EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débit incendie estimé.
        /// </summary>
        public static string EstimatedWaterFlow {
            get {
                return ResourceManager.GetString("EstimatedWaterFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de fax.
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étage.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de garage.
        /// </summary>
        public static string GarageType {
            get {
                return ResourceManager.GetString("GarageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée de gaz.
        /// </summary>
        public static string GasInlet {
            get {
                return ResourceManager.GetString("GasInlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du guide.
        /// </summary>
        public static string GuideNumber {
            get {
                return ResourceManager.GetString("GuideNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant .
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type du panneau d&apos;alarme.
        /// </summary>
        public static string IdAlarmPanelType {
            get {
                return ResourceManager.GetString("IdAlarmPanelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bâtiment.
        /// </summary>
        public static string IdBuilding {
            get {
                return ResourceManager.GetString("IdBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomalie de bâtiment.
        /// </summary>
        public static string IdBuildingAnomaly {
            get {
                return ResourceManager.GetString("IdBuildingAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipalité.
        /// </summary>
        public static string IdCity {
            get {
                return ResourceManager.GetString("IdCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de municipalité.
        /// </summary>
        public static string IdCityType {
            get {
                return ResourceManager.GetString("IdCityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string IdCountry {
            get {
                return ResourceManager.GetString("IdCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRC.
        /// </summary>
        public static string IdCounty {
            get {
                return ResourceManager.GetString("IdCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borne incendie.
        /// </summary>
        public static string IdFireHydrant {
            get {
                return ResourceManager.GetString("IdFireHydrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type du raccord .
        /// </summary>
        public static string IdFireHydrantConnectionType {
            get {
                return ResourceManager.GetString("IdFireHydrantConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de la borne incendie.
        /// </summary>
        public static string IdFireHydrantType {
            get {
                return ResourceManager.GetString("IdFireHydrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service sécurité incendie.
        /// </summary>
        public static string IdFireSafetyDepartment {
            get {
                return ResourceManager.GetString("IdFireSafetyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matière dangereuse.
        /// </summary>
        public static string IdHazardousMaterial {
            get {
                return ResourceManager.GetString("IdHazardousMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transversale.
        /// </summary>
        public static string IdIntersection {
            get {
                return ResourceManager.GetString("IdIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voie de circulation.
        /// </summary>
        public static string IdLane {
            get {
                return ResourceManager.GetString("IdLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code générique.
        /// </summary>
        public static string IdLaneGenericCode {
            get {
                return ResourceManager.GetString("IdLaneGenericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code public.
        /// </summary>
        public static string IdPublicCode {
            get {
                return ResourceManager.GetString("IdPublicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau de risque.
        /// </summary>
        public static string IdRiskLevel {
            get {
                return ResourceManager.GetString("IdRiskLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure.
        /// </summary>
        public static string IdUnitOfMeasure {
            get {
                return ResourceManager.GetString("IdUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure du diamètre.
        /// </summary>
        public static string IdUnitOfMeasureDiameter {
            get {
                return ResourceManager.GetString("IdUnitOfMeasureDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure de débit d&apos;eau estimé.
        /// </summary>
        public static string IdUnitOfMeasureEstimatedWaterFlow {
            get {
                return ResourceManager.GetString("IdUnitOfMeasureEstimatedWaterFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure de la hauteur.
        /// </summary>
        public static string IdUnitOfMeasureHeight {
            get {
                return ResourceManager.GetString("IdUnitOfMeasureHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure de la pression.
        /// </summary>
        public static string IdUnitOfMeasurePressure {
            get {
                return ResourceManager.GetString("IdUnitOfMeasurePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure du taux.
        /// </summary>
        public static string IdUnitOfMeasureRate {
            get {
                return ResourceManager.GetString("IdUnitOfMeasureRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur doit être supérieure ou égale à 0..
        /// </summary>
        public static string InferiorToZeroValue {
            get {
                return ResourceManager.GetString("InferiorToZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il doit y avoir au moins 2 éléments..
        /// </summary>
        public static string InvalidCount {
            get {
                return ResourceManager.GetString("InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur invalide..
        /// </summary>
        public static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur invalide..
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est affaibli.
        /// </summary>
        public static string IsWeakened {
            get {
                return ResourceManager.GetString("IsWeakened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisations.
        /// </summary>
        public static string Localizations {
            get {
                return ResourceManager.GetString("Localizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;adresse.
        /// </summary>
        public static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricule.
        /// </summary>
        public static string Matricule {
            get {
                return ResourceManager.GetString("Matricule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de mesure.
        /// </summary>
        public static string MeasureType {
            get {
                return ResourceManager.GetString("MeasureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de fichier.
        /// </summary>
        public static string MimeType {
            get {
                return ResourceManager.GetString("MimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur manquante..
        /// </summary>
        public static string MissingValue {
            get {
                return ResourceManager.GetString("MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur nulle..
        /// </summary>
        public static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre d&apos;appartements.
        /// </summary>
        public static string NumberOfAppartment {
            get {
                return ResourceManager.GetString("NumberOfAppartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de bâtiments.
        /// </summary>
        public static string NumberOfBuilding {
            get {
                return ResourceManager.GetString("NumberOfBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre d&apos;étages.
        /// </summary>
        public static string NumberOfFloor {
            get {
                return ResourceManager.GetString("NumberOfFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres informations.
        /// </summary>
        public static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre numéro de téléphone.
        /// </summary>
        public static string OtherNumber {
            get {
                return ResourceManager.GetString("OtherNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension de l&apos;autre numéro de téléphone.
        /// </summary>
        public static string OtherNumberExtension {
            get {
                return ResourceManager.GetString("OtherNumberExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de téléavertisseur.
        /// </summary>
        public static string PagerCode {
            get {
                return ResourceManager.GetString("PagerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléavertisseur.
        /// </summary>
        public static string PagerNumber {
            get {
                return ResourceManager.GetString("PagerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro d&apos;extension du téléphone.
        /// </summary>
        public static string PhoneNumberExtension {
            get {
                return ResourceManager.GetString("PhoneNumberExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position physique.
        /// </summary>
        public static string PhysicalPosition {
            get {
                return ResourceManager.GetString("PhysicalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endroit.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérateur de la pression.
        /// </summary>
        public static string PressureOperatorType {
            get {
                return ResourceManager.GetString("PressureOperatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérateur du taux.
        /// </summary>
        public static string RateOperatorType {
            get {
                return ResourceManager.GetString("RateOperatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réagit à l&apos;eau.
        /// </summary>
        public static string ReactToWater {
            get {
                return ResourceManager.GetString("ReactToWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCIAN.
        /// </summary>
        public static string Scian {
            get {
                return ResourceManager.GetString("Scian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secteur.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Périmètre de sécurité.
        /// </summary>
        public static string SecurityPerimeter {
            get {
                return ResourceManager.GetString("SecurityPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite.
        /// </summary>
        public static string Suite {
            get {
                return ResourceManager.GetString("Suite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conduite d&apos;alimentation.
        /// </summary>
        public static string SupplyLine {
            get {
                return ResourceManager.GetString("SupplyLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de réservoir.
        /// </summary>
        public static string TankType {
            get {
                return ResourceManager.GetString("TankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur ne doit pas dépasser .
        /// </summary>
        public static string TooLong {
            get {
                return ResourceManager.GetString("TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur doit être plus grande que .
        /// </summary>
        public static string TooShort {
            get {
                return ResourceManager.GetString("TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxique lorsque inhalée .
        /// </summary>
        public static string ToxicInhalationHazard {
            get {
                return ResourceManager.GetString("ToxicInhalationHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur inconnue..
        /// </summary>
        public static string UnknownValue {
            get {
                return ResourceManager.GetString("UnknownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description d&apos;utilisation.
        /// </summary>
        public static string UtilisationDescription {
            get {
                return ResourceManager.GetString("UtilisationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mur.
        /// </summary>
        public static string Wall {
            get {
                return ResourceManager.GetString("Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordonnées géographiques.
        /// </summary>
        public static string WktCoordinates {
            get {
                return ResourceManager.GetString("WktCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année de construction.
        /// </summary>
        public static string YearOfConstruction {
            get {
                return ResourceManager.GetString("YearOfConstruction", resourceCulture);
            }
        }
    }
}
